### ISSUE TITLE
Couldnt connect to Database

### ISSUE THREAD

**Issue by parthkris13** [bipinsai/ChatBot-Buy-Sell-BPHC#1]
Its displaying that the database is locked.

**Comment by bipinsai** [comment]
It's because another connection is already accessing the database. By specifying a timeout (timeout=10 in this case), you're giving the other thread time to complete its transaction and close the connection, and then your connection will be able to proceed.

Things which you can do : 
1. Save the changes on the DB Browser and try running the code again.
2. Close the DB Browser if you are using it .
3. Delete any cache files which appear in the same folder as the Database file .
4. https://stackoverflow.com/questions/2740806/python-sqlite-database-is-locked
